name: Zip Bomb Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Git user for committing
    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    # Step 3: Install 7-Zip for robust extraction
    - name: Install 7-Zip
      run: sudo apt-get install -y p7zip-full

    # Step 4: Create directory for extracted files
    - name: Create extracted_files2 directory
      run: mkdir -p extracted_files2

    # Step 5: Extract files one by one and process them
    - name: Extract and process each file sequentially
      run: |
        ulimit -n 65535   # Increase file descriptors limit
        ulimit -v unlimited   # Allow unlimited virtual memory

        # List all the files in the ZIP archive
        7z l zbbig2.zip > file_list.txt

        # Loop through each file in the ZIP
        while IFS= read -r file; do
          echo "Extracting file: $file"
          
          # Extract the individual file from the ZIP
          7z e zbbig2.zip "$file" -oextracted_files2 || echo "Extraction failed for $file"
          
          # Check if the file exists after extraction
          if [ -f "extracted_files2/$file" ]; then
            echo "Processing $file"
          
            # Add, commit, and push the file
            git add extracted_files2/*
            git commit -m "Add extracted file $file"
            git push || echo "Push failed for $file"
          
            # Delete the file after processing to free up space
            rm -f extracted_files2/*
          else
            echo "File $file not found after extraction"
          fi
        done < file_list.txt
