name: Zip Bomb Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Git user for committing
    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    # Step 3: Install p7zip for robust extraction
    - name: Install 7-Zip
      run: sudo apt-get install -y p7zip-full

    # Step 4: Create directory for extracted files
    - name: Create extracted_files2 directory
      run: mkdir -p extracted_files2

    # Step 5: Extract the ZIP file in chunks using 7z
    - name: Extract and process ZIP file in chunks
      run: |
        ulimit -n 65535   # Increase file descriptors limit
        ulimit -v unlimited   # Allow unlimited virtual memory
        
        # Loop through chunks
        chunk_size=500M  # Define the size of each chunk
        while :; do
          echo "Extracting next chunk..."
          
          # Extract a portion of the ZIP file
          7z x zbbig2.zip -oextracted_files2 -bb0 -y -v${chunk_size}
          
          # Check if extraction yielded any files
          if [ "$(ls -A extracted_files2)" ]; then
            # Step 6: Check the size of extracted files (log the output)
            du -sh extracted_files2 || echo "Size check failed"
          
            # Step 7: Commit the extracted files to the repository (handling Git large file limits)
            git add extracted_files2/*
            git commit -m "Add extracted chunk from zbbig2.zip"
            git push || echo "Push failed due to large files"
          
            # Step 8: Clean up the extracted files to free up space
            rm -rf extracted_files2/*
          else
            echo "No more files to extract. Exiting..."
            break
          fi
        done
